
name: Deploy to Dev

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: "Deploy to Dev Environment"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true

      - name: Build
        run: pnpm build

      - name: Setup Google Cloud Credentials
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}"

      - name: Deploy to Firebase Dev
        uses: firebase/firebase-tools-action@v0
        with:
          projectId: proyecto-qx-dev
          args: "deploy --only hosting,firestore,functions"
